# Generated by Django 5.1.15 on 2026-09-03 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='core.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='core.taller')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, max_length=30)),
                ('equipo', models.CharField(max_length=150)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'Diagnóstico'), ('en_reparacion', 'En reparación'), ('listo', 'Listo para retiro'), ('entregado', 'Entregado')], default='recibido', max_length=20)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='core.taller')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='core.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='core.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.repuesto')),
            ],
            options={
                'unique_together': {('orden', 'repuesto')},
            },
        ),
    ]
