# Generated by Django 5.1.15 on 2026-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repuesto_tecnico_ordentrabajo_ordenrepuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
